### DISCUSSION TITLE
Add Option to Publish Raw Usage Data to Custom MQTT Topic

### DISCUSSION THREAD

**Discussion by zachowj** [thor0215/hassio-xfinity-usage#40] [Ideas]
I would like to propose a feature that allows users to define a custom MQTT topic for publishing raw usage data from Xfinity. This can be achieved by using an environment variable, such as MQTT_RAW_USAGE_TOPIC.

The desired functionality would enable the raw usage data to be published to the specified MQTT topic without any modifications.

Currently, I have implemented a workaround in a cloned repository, but it is not clean. I utilize historical data in Home Assistant, which I then process through Node-RED to create sensors that output daily usage and remaining time for the month.

Thank you for considering this enhancement!

**Comment by thor0215** [comment]
Can you give me an example of the raw data you want?

**Reply by zachowj** [reply]
https://github.com/thor0215/hassio-xfinity-usage/blob/84e25a2ffcbf791dc96f266970ce4d93810d8752/xfinity-usage/xfinity_usage_addon.py#L537

All of `json_data`

**Comment by thor0215** [comment]
You would like this entire JSON to be in the attributes?

`{
    "accountNumber": "0000000000000000",
    "courtesyUsed": 0,
    "courtesyRemaining": 1,
    "courtesyAllowed": 1,
    "courtesyMonths": [
        "03/2023"
    ],
    "inPaidOverage": false,
    "displayUsage": true,
    "usageMonths": [
        {
            "policyName": "1.2 Terabyte Data Plan",
            "startDate": "10/01/2023",
            "endDate": "10/31/2023",
            "homeUsage": 1045,
            "wifiUsage": 0,
            "totalUsage": 1045,
            "allowableUsage": 1229,
            "unitOfMeasure": "GB",
            "displayUsage": true,
            "devices": [
                {
                    "id": "AA:BB:CC:DD:11:22",
                    "usage": 1053,
                    "policyName": "XI Superfast"
                }
            ],
            "additionalBlocksUsed": 0,
            "additionalCostPerBlock": 10,
            "additionalUnitsPerBlock": 50,
            "additionalBlockSize": 50,
            "additionalIncluded": 0,
            "additionalUsed": 0,
            "additionalPercentUsed": 0.0,
            "additionalRemaining": 0,
            "billableOverage": 0,
            "overageCharges": 0.0,
            "overageUsed": 0,
            "currentCreditAmount": 0,
            "maxCreditAmount": 0,
            "maximumOverageCharge": 100,
            "policy": "limited"
        },
        {
            "policyName": "1.2 Terabyte Data Plan",
            "startDate": "11/01/2023",
            "endDate": "11/30/2023",
            "homeUsage": 797,
            "wifiUsage": 0,
            "totalUsage": 797,
            "allowableUsage": 1229,
            "unitOfMeasure": "GB",
            "displayUsage": true,
            "devices": [
                {
                    "id": "AA:BB:CC:DD:11:22",
                    "usage": 804,
                    "policyName": "XI Superfast"
                }
            ],
            "additionalBlocksUsed": 0,
            "additionalCostPerBlock": 10,
            "additionalUnitsPerBlock": 50,
            "additionalBlockSize": 50,
            "additionalIncluded": 0,
            "additionalUsed": 0,
            "additionalPercentUsed": 0.0,
            "additionalRemaining": 0,
            "billableOverage": 0,
            "overageCharges": 0.0,
            "overageUsed": 0,
            "currentCreditAmount": 0,
            "maxCreditAmount": 0,
            "maximumOverageCharge": 100,
            "policy": "limited"
        },
        {
            "policyName": "1.2 Terabyte Data Plan",
            "startDate": "12/01/2023",
            "endDate": "12/31/2023",
            "homeUsage": 1064,
            "wifiUsage": 0,
            "totalUsage": 1064,
            "allowableUsage": 1229,
            "unitOfMeasure": "GB",
            "displayUsage": true,
            "devices": [
                {
                    "id": "AA:BB:CC:DD:11:22",
                    "usage": 1075,
                    "policyName": "XI Superfast"
                }
            ],
            "additionalBlocksUsed": 0,
            "additionalCostPerBlock": 10,
            "additionalUnitsPerBlock": 50,
            "additionalBlockSize": 50,
            "additionalIncluded": 0,
            "additionalUsed": 0,
            "additionalPercentUsed": 0.0,
            "additionalRemaining": 0,
            "billableOverage": 0,
            "overageCharges": 0.0,
            "overageUsed": 0,
            "currentCreditAmount": 0,
            "maxCreditAmount": 0,
            "maximumOverageCharge": 100,
            "policy": "limited"
        },
        {
            "policyName": "1.2 Terabyte Data Plan",
            "startDate": "01/01/2024",
            "endDate": "01/31/2024",
            "homeUsage": 1003,
            "wifiUsage": 0,
            "totalUsage": 1003,
            "allowableUsage": 1229,
            "unitOfMeasure": "GB",
            "displayUsage": true,
            "devices": [
                {
                    "id": "AA:BB:CC:DD:11:22",
                    "usage": 1010,
                    "policyName": "XI Superfast"
                }
            ],
            "additionalBlocksUsed": 0,
            "additionalCostPerBlock": 10,
            "additionalUnitsPerBlock": 50,
            "additionalBlockSize": 50,
            "additionalIncluded": 0,
            "additionalUsed": 0,
            "additionalPercentUsed": 0.0,
            "additionalRemaining": 0,
            "billableOverage": 0,
            "overageCharges": 0.0,
            "overageUsed": 0,
            "currentCreditAmount": 0,
            "maxCreditAmount": 0,
            "maximumOverageCharge": 100,
            "policy": "limited"
        },
        {
            "policyName": "1.2 Terabyte Data Plan",
            "startDate": "02/01/2024",
            "endDate": "02/29/2024",
            "homeUsage": 558,
            "wifiUsage": 0,
            "totalUsage": 558,
            "allowableUsage": 1229,
            "unitOfMeasure": "GB",
            "displayUsage": true,
            "devices": [
                {
                    "id": "AA:BB:CC:DD:11:22",
                    "usage": 564,
                    "policyName": "XI Superfast"
                }
            ],
            "additionalBlocksUsed": 0,
            "additionalCostPerBlock": 10,
            "additionalUnitsPerBlock": 50,
            "additionalBlockSize": 50,
            "additionalIncluded": 0,
            "additionalUsed": 0,
            "additionalPercentUsed": 0.0,
            "additionalRemaining": 0,
            "billableOverage": 0,
            "overageCharges": 0.0,
            "overageUsed": 0,
            "currentCreditAmount": 0,
            "maxCreditAmount": 0,
            "maximumOverageCharge": 100,
            "policy": "limited"
        },
        {
            "policyName": "1.2 Terabyte Data Plan",
            "startDate": "03/01/2024",
            "endDate": "03/31/2024",
            "homeUsage": 705,
            "wifiUsage": 0,
            "totalUsage": 705,
            "allowableUsage": 1229,
            "unitOfMeasure": "GB",
            "displayUsage": true,
            "devices": [
                {
                    "id": "AA:BB:CC:DD:11:22",
                    "usage": 717,
                    "policyName": "XI Superfast"
                }
            ],
            "additionalBlocksUsed": 0,
            "additionalCostPerBlock": 10,
            "additionalUnitsPerBlock": 50,
            "additionalBlockSize": 50,
            "additionalIncluded": 0,
            "additionalUsed": 0,
            "additionalPercentUsed": 0.0,
            "additionalRemaining": 0,
            "billableOverage": 0,
            "overageCharges": 0.0,
            "overageUsed": 0,
            "currentCreditAmount": 0,
            "maxCreditAmount": 0,
            "maximumOverageCharge": 100,
            "policy": "limited"
        },
        {
            "policyName": "1.2 Terabyte Data Plan",
            "startDate": "04/01/2024",
            "endDate": "04/30/2024",
            "homeUsage": 585,
            "wifiUsage": 0,
            "totalUsage": 585,
            "allowableUsage": 1229,
            "unitOfMeasure": "GB",
            "displayUsage": true,
            "devices": [
                {
                    "id": "AA:BB:CC:DD:11:22",
                    "usage": 592,
                    "policyName": "XI Superfast"
                }
            ],
            "additionalBlocksUsed": 0,
            "additionalCostPerBlock": 10,
            "additionalUnitsPerBlock": 50,
            "additionalBlockSize": 50,
            "additionalIncluded": 0,
            "additionalUsed": 0,
            "additionalPercentUsed": 0.0,
            "additionalRemaining": 0,
            "billableOverage": 0,
            "overageCharges": 0.0,
            "overageUsed": 0,
            "currentCreditAmount": 0,
            "maxCreditAmount": 0,
            "maximumOverageCharge": 100,
            "policy": "limited"
        },
        {
            "policyName": "1.2 Terabyte Data Plan",
            "startDate": "05/01/2024",
            "endDate": "05/31/2024",
            "homeUsage": 872,
            "wifiUsage": 0,
            "totalUsage": 872,
            "allowableUsage": 1229,
            "unitOfMeasure": "GB",
            "displayUsage": true,
            "devices": [
                {
                    "id": "AA:BB:CC:DD:11:22",
                    "usage": 879,
                    "policyName": "XI Superfast"
                }
            ],
            "additionalBlocksUsed": 0,
            "additionalCostPerBlock": 10,
            "additionalUnitsPerBlock": 50,
            "additionalBlockSize": 50,
            "additionalIncluded": 0,
            "additionalUsed": 0,
            "additionalPercentUsed": 0.0,
            "additionalRemaining": 0,
            "billableOverage": 0,
            "overageCharges": 0.0,
            "overageUsed": 0,
            "currentCreditAmount": 0,
            "maxCreditAmount": 0,
            "maximumOverageCharge": 100,
            "policy": "limited"
        },
        {
            "policyName": "1.2 Terabyte Data Plan",
            "startDate": "06/01/2024",
            "endDate": "06/30/2024",
            "homeUsage": 975,
            "wifiUsage": 0,
            "totalUsage": 975,
            "allowableUsage": 1229,
            "unitOfMeasure": "GB",
            "displayUsage": true,
            "devices": [
                {
                    "id": "AA:BB:CC:DD:11:22",
                    "usage": 983,
                    "policyName": "XI Superfast"
                }
            ],
            "additionalBlocksUsed": 0,
            "additionalCostPerBlock": 10,
            "additionalUnitsPerBlock": 50,
            "additionalBlockSize": 50,
            "additionalIncluded": 0,
            "additionalUsed": 0,
            "additionalPercentUsed": 0.0,
            "additionalRemaining": 0,
            "billableOverage": 0,
            "overageCharges": 0.0,
            "overageUsed": 0,
            "currentCreditAmount": 0,
            "maxCreditAmount": 0,
            "maximumOverageCharge": 100,
            "policy": "limited"
        },
        {
            "policyName": "1.2 Terabyte Data Plan",
            "startDate": "07/01/2024",
            "endDate": "07/31/2024",
            "homeUsage": 816,
            "wifiUsage": 0,
            "totalUsage": 816,
            "allowableUsage": 1229,
            "unitOfMeasure": "GB",
            "displayUsage": true,
            "devices": [
                {
                    "id": "AA:BB:CC:DD:11:22",
                    "usage": 823,
                    "policyName": "XI Superfast"
                }
            ],
            "additionalBlocksUsed": 0,
            "additionalCostPerBlock": 10,
            "additionalUnitsPerBlock": 50,
            "additionalBlockSize": 50,
            "additionalIncluded": 0,
            "additionalUsed": 0,
            "additionalPercentUsed": 0.0,
            "additionalRemaining": 0,
            "billableOverage": 0,
            "overageCharges": 0.0,
            "overageUsed": 0,
            "currentCreditAmount": 0,
            "maxCreditAmount": 0,
            "maximumOverageCharge": 100,
            "policy": "limited"
        },
        {
            "policyName": "1.2 Terabyte Data Plan",
            "startDate": "08/01/2024",
            "endDate": "08/31/2024",
            "homeUsage": 1049,
            "wifiUsage": 0,
            "totalUsage": 1049,
            "allowableUsage": 1229,
            "unitOfMeasure": "GB",
            "displayUsage": true,
            "devices": [
                {
                    "id": "AA:BB:CC:DD:11:22",
                    "usage": 1056,
                    "policyName": "XI Superfast"
                }
            ],
            "additionalBlocksUsed": 0,
            "additionalCostPerBlock": 10,
            "additionalUnitsPerBlock": 50,
            "additionalBlockSize": 50,
            "additionalIncluded": 0,
            "additionalUsed": 0,
            "additionalPercentUsed": 0.0,
            "additionalRemaining": 0,
            "billableOverage": 0,
            "overageCharges": 0.0,
            "overageUsed": 0,
            "currentCreditAmount": 0,
            "maxCreditAmount": 0,
            "maximumOverageCharge": 100,
            "policy": "limited"
        },
        {
            "policyName": "1.2 Terabyte Data Plan",
            "startDate": "09/01/2024",
            "endDate": "09/30/2024",
            "homeUsage": 580,
            "wifiUsage": 0,
            "totalUsage": 580,
            "allowableUsage": 1229,
            "unitOfMeasure": "GB",
            "displayUsage": true,
            "devices": [
                {
                    "id": "AA:BB:CC:DD:11:22",
                    "usage": 585,
                    "policyName": "XI Superfast"
                }
            ],
            "additionalBlocksUsed": 0,
            "additionalCostPerBlock": 10,
            "additionalUnitsPerBlock": 50,
            "additionalBlockSize": 50,
            "additionalIncluded": 0,
            "additionalUsed": 0,
            "additionalPercentUsed": 0.0,
            "additionalRemaining": 0,
            "billableOverage": 0,
            "overageCharges": 0.0,
            "overageUsed": 0,
            "currentCreditAmount": 0,
            "maxCreditAmount": 0,
            "maximumOverageCharge": 100,
            "policy": "limited"
        }
    ]
}`

**Comment by thor0215** [comment]
What if I include a new attribute for the sensor called raw_usage and put the entire raw usage json received from Xfinity underneath that?

**Reply by zachowj** [reply]
My initial thought was to post this to a custom MQTT topic, as I don’t necessarily need it in Home Assistant. However, if it’s easier to include it in the sensor attributes topic, that works for me as well.

**Comment by thor0215** [comment]
I've got a dev branch, 0.0.12.8.1 that includes this. It will just post the full usage data to the xfinity topic at the root instead of under homeassistant.  I'm going to let this run for a few days in my lab and see how it goes.

**Reply by zachowj** [reply]
Confirmed that everything works correctly for me so far.

However, I encountered an issue with the default entry point when running in a standalone container (outside of Hassio). I haven't had time to troubleshoot fully yet, but I’ll create a detailed issue when I can. 

In the meantime, I resolved it by using a custom entry point in my Docker Compose file:

```yaml
entrypoint: /bin/sh -c "python3 -Wignore /xfinity_usage_addon.py"
```

**Comment by thor0215** [comment]
Do you need the MQTT raw data topic to be retained in the MQTT server or just published?  I'm working on a dashboard template that would show past month and usage in a table, but I can only get the mqtt trigger sensor to work if I do not retain the topic.

**Reply by zachowj** [reply]
Retain is preferred, as it prevents you from waiting for another update after a reboot.

Here's my dashboard, where I use Node-RED to parse the data and create the sensor:

![image](https://github.com/user-attachments/assets/11384623-1df5-4be0-bc67-d9609c04cf85)

**Reply by zachowj** [reply]
Can you make it configurable via environment variables?

**Reply by thor0215** [reply]
I had a bug in my template trigger sensor, so nevermind, I will be keeping the topic with the retain option. I would love to see instructions on how to setup a dashboard like screenshot above.  I made a simple markdown table like this:

![image](https://github.com/user-attachments/assets/b3436e71-0c33-409e-8686-b2ca2c380c42)

I plan to provide documentation on how to set that up.

**Reply by zachowj** [reply]
Here’s the raw YAML I used, originally found on the Home Assistant forums and then modified to fit my needs. Most of the sensor names should be self-explanatory.

```yaml
type: custom:vertical-stack-in-card
title: Xfinity Usage
cards:
  - type: custom:mini-graph-card
    icon: mdi:download-network
    entities:
      - entity: sensor.xfinity_current_usage
        name: Xfinity Data
        show_graph: false
        aggregate_func: last
      - entity: sensor.xfinity_todays_usage
        name: Xfinity Data
        show_graph: true
        show_state: true
        aggregate_func: last
    hours_to_show: 672
    group_by: date
    font_size_header: 14
    font_size: 100
    line_width: 3
    group: false
    lower_bound: 0
    animate: true
    smoothing: false
    color_thresholds:
      - value: 0
        color: rgba(42, 187, 155, 0.9)
      - value: 30
        color: var(--label-badge-yellow)
      - value: 40
        color: "#b93829"
    show:
      points: false
      labels: false
      labels_secondary: false
      legend: false
      graph: bar
      icon: false
      name: false
    tap_action: none
  - type: entities
    show_header_toggle: false
    entities:
      - type: custom:bar-card
        name: Xfinity
        icon: mdi:download-network
        entity: sensor.xfinity_usage
        attribute: percent
        entity_row: true
        max: 100
        unit_of_measurement: "%"
        positions:
          name: "off"
          indicator: "off"
          value: outside
        height: 30px
        card_mod:
          style: >-
            ha-card { border-width: 0 } bar-card-background { margin-right: 13px
            !important; margin-top: 5px !important; } 
      - type: custom:bar-card
        name: Month Percent
        icon: mdi:calendar-arrow-right
        entity: sensor.percent_of_hours_passed
        entity_row: true
        max: 100
        positions:
          name: "off"
          indicator: "off"
          value: outside
        height: 30px
        card_mod:
          style: >-
            ha-card { border-width: 0; width: 100%; } bar-card-background {
            margin-right: 13px !important; margin-top: 5px !important; }
      - name: Average used per day
        entity: sensor.xfinity_avg_current_daily_usage
      - name: Average remaining per day
        entity: sensor.xfinity_remaining_daily_usage
  - type: markdown
    card_mod:
      style: |
        ha-card { border-width: 0; }
        ha-markdown.no-header { padding-top: 3 !important; text-align: center; }
        ha-markdown { color: var(--secondary-text-color); }
    content: >-
      {% set data_remaining = state_attr('sensor.xfinity_usage',
      'remaining_usage') %} {% set days_remaining =
      state_attr('sensor.xfinity_usage', 'days_left_in_month') %}

      {% if data_remaining >= 0 -%}
        **{{ data_remaining }}** GB remaining to use over the next {{ days_remaining }} {% if days_remaining != 1 %}days{% else %}day{% endif %}
      {%- else -%}
        **{{ -data_remaining }} GB over with {{ days_remaining }} {% if days_remaining != 1 %}days{% else %}day{% endif %} remaining**
        _Xfinity charges $10 per 50 GB of data_
      {%- endif %}

      {%- macro formatvalue(name, value, sep='') %}     {{ '{} {}'.format(value,
      name) if value >= 1 else '' }} {%- endmacro %} {%- set time =
      ((as_timestamp(now()) -
      as_timestamp(states.sensor.xfinity_usage.last_reported))) %} {%- set
      minutes = formatvalue('minute', (time % 3600) // 60, '') %} {%- set hours
      = formatvalue('hour', (time % 86400) // 3600, ', ') %} {%- set days =
      formatvalue('day', time // 86400, ', ') %}

      Updated {{ 'Less than 1 min' if time < 60 else days ~ hours ~ minutes }}
      ago
  - type: entities
    show_header_toggle: false
    entities:
      - type: custom:bar-card
        entity: sensor.xfinity_month_usage_0
        unit_of_measurement: GB
        entity_row: true
        max: 1229
        severity:
          - from: 950
            to: 1100
            color: var(--label-badge-yellow)
          - from: 1100
            to: 1229
            color: "#b93829"
        positions:
          icon: "off"
        height: 30px
        tap_action: none
        card_mod:
          style: "ha-card { border-width: 0 }"
      - type: custom:bar-card
        entity: sensor.xfinity_month_usage_1
        unit_of_measurement: GB
        entity_row: true
        max: 1229
        severity:
          - from: 950
            to: 1100
            color: var(--label-badge-yellow)
          - from: 1100
            to: 1229
            color: "#b93829"
        positions:
          icon: "off"
        height: 30px
        tap_action: none
        card_mod:
          style: "ha-card { border-width: 0 }"
      - type: custom:bar-card
        entity: sensor.xfinity_month_usage_2
        unit_of_measurement: GB
        entity_row: true
        max: 1229
        severity:
          - from: 950
            to: 1100
            color: var(--label-badge-yellow)
          - from: 1100
            to: 1229
            color: "#b93829"
        positions:
          icon: "off"
        height: 30px
        tap_action: none
        card_mod:
          style: "ha-card { border-width: 0 }"
      - type: custom:bar-card
        entity: sensor.xfinity_month_usage_3
        unit_of_measurement: GB
        entity_row: true
        max: 1229
        severity:
          - from: 950
            to: 1100
            color: var(--label-badge-yellow)
          - from: 1100
            to: 1229
            color: "#b93829"
        positions:
          icon: "off"
        height: 30px
        tap_action: none
        card_mod:
          style: "ha-card { border-width: 0 }"
      - type: custom:bar-card
        entity: sensor.xfinity_month_usage_4
        unit_of_measurement: GB
        entity_row: true
        max: 1229
        severity:
          - from: 950
            to: 1100
            color: var(--label-badge-yellow)
          - from: 1100
            to: 1229
            color: "#b93829"
        positions:
          icon: "off"
        height: 30px
        tap_action: none
        card_mod:
          style: "ha-card { border-width: 0 }"
      - type: custom:bar-card
        entity: sensor.xfinity_month_usage_5
        unit_of_measurement: GB
        entity_row: true
        max: 1229
        severity:
          - from: 950
            to: 1100
            color: var(--label-badge-yellow)
          - from: 1100
            to: 1229
            color: "#b93829"
        positions:
          icon: "off"
        height: 30px
        tap_action: none
        card_mod:
          style: "ha-card { border-width: 0 }"
      - type: custom:bar-card
        entity: sensor.xfinity_month_usage_6
        unit_of_measurement: GB
        entity_row: true
        max: 1229
        severity:
          - from: 950
            to: 1100
            color: var(--label-badge-yellow)
          - from: 1100
            to: 1229
            color: "#b93829"
        positions:
          icon: "off"
        height: 30px
        tap_action: none
        card_mod:
          style: "ha-card { border-width: 0 }"
      - type: custom:bar-card
        entity: sensor.xfinity_month_usage_7
        unit_of_measurement: GB
        entity_row: true
        max: 1229
        severity:
          - from: 950
            to: 1100
            color: var(--label-badge-yellow)
          - from: 1100
            to: 1229
            color: "#b93829"
        positions:
          icon: "off"
        height: 30px
        tap_action: none
        card_mod:
          style: "ha-card { border-width: 0 }"
      - type: custom:bar-card
        entity: sensor.xfinity_month_usage_8
        unit_of_measurement: GB
        entity_row: true
        max: 1229
        severity:
          - from: 950
            to: 1100
            color: var(--label-badge-yellow)
          - from: 1100
            to: 1229
            color: "#b93829"
        positions:
          icon: "off"
        height: 30px
        tap_action: none
        card_mod:
          style: "ha-card { border-width: 0 }"
      - type: custom:bar-card
        entity: sensor.xfinity_month_usage_9
        unit_of_measurement: GB
        entity_row: true
        max: 1229
        severity:
          - from: 950
            to: 1100
            color: var(--label-badge-yellow)
          - from: 1100
            to: 1229
            color: "#b93829"
        positions:
          icon: "off"
        height: 30px
        tap_action: none
        card_mod:
          style: "ha-card { border-width: 0 }"
      - type: custom:bar-card
        entity: sensor.xfinity_month_usage_10
        unit_of_measurement: GB
        entity_row: true
        max: 1229
        severity:
          - from: 950
            to: 1100
            color: var(--label-badge-yellow)
          - from: 1100
            to: 1229
            color: "#b93829"
        positions:
          icon: "off"
        height: 30px
        tap_action: none
        card_mod:
          style: "ha-card { border-width: 0 }"
```
