### ISSUE TITLE
Docker container stops after successfully pulling usage data

### ISSUE THREAD

**Issue by yuejon** [thor0215/hassio-xfinity-usage#42]
I recently switched from [this repository as per zachowj's recommendation](https://github.com/zachowj/xfinity-data-usage/issues/337#issuecomment-2372522294) and I'm running it as a docker container. So far, this has been more successful at pulling usage data. However, I am noticing that after a successful pull, the container stops and if I have the container set to restart automatically, it instantly initiates another pull. So it is effectively not using the polling rate that I have set and I do not want to trigger another ban with such frequent polling.

![image](https://github.com/user-attachments/assets/f5321564-7af5-47a7-aa6b-42b33f4ebda9)

This is the docker compose I used to set up my container:
```
services:
  xfinity-usage:
    image: ghcr.io/thor0215/hassio-xfinity-usage-amd64:latest
    container_name: Xfinity-Usage
    entrypoint: /bin/sh -c "python3 -Wignore /xfinity_usage_addon.py"
#    restart: unless-stopped
    environment:
      TZ: America/Chicago
      XFINITY_USERNAME: <username>
      XFINITY_PASSWORD: <password>
      MQTT_SERVICE: true
      MQTT_HOST: <ip>
      MQTT_PORT: 1883
      POLLING_RATE: 10800
      PAGE_TIMEOUT: 60
```
